### ISSUE TITLE
youku error

### ISSUE THREAD

**Issue by zlzdp** [EvilCult/Video-Downloader#31]
souce:
http://v.youku.com/v_show/id_XMTczOTQ0MzY3Ng==.html?from=y1.6-91.3.1.f2af377a8c3311e5b2ad

error:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "C:\Users\Engin\Desktop\Video-Downloader\guiClass.py", line 136, in __get
Url
    urlList = getClass.chaseUrl()
  File "C:\Users\Engin\Desktop\Video-Downloader\Module\youkuClass.py", line 27,
in chaseUrl
    fileUrl = self.__getVideoFileUrl(info)
  File "C:\Users\Engin\Desktop\Video-Downloader\Module\youkuClass.py", line 71,
in __getVideoFileUrl
    typeInfo = self.__getTypeCode(self.videoTypeList[self.videoType], videoInfo[
'data']['stream'])
  File "C:\Users\Engin\Desktop\Video-Downloader\Module\youkuClass.py", line 111,
 in __getTypeCode
    'videoTypeCode': typeCode
UnboundLocalError: local variable 'typeCode' referenced before assignment

**Comment by EvilCult** [comment]
错误的原因是选择下载的清晰度，当前视频并没有。
正在想一个更好的解决办法。。。。（想的或许有点复杂了，也许简简单单出个提示就好。。）

更深层次的原因：优酷的清晰度规范好乱mp4hd3，hd3神马的，我现在已经有点傻傻分不清楚了。。

anyway，下个版本更新会解决这个问题。
