### ISSUE TITLE
ImportError: No module named 'ttk'

### ISSUE THREAD

**Issue by moboard** [EvilCult/Video-Downloader#33]
arch，python2,python3都有。
python guiClass.py

```

Traceback (most recent call last):
  File "guiClass.py", line 4, in <module>
    import ttk 
ImportError: No module named 'Thinker'
```

把Tkinter改成小写的tkinter，再运行显示 

```
Traceback (most recent call last):
  File "guiClass.py", line 4, in <module>
    import ttk 
ImportError: No module named 'ttk'

系统没有ttk相关的软件包，请教下怎么解决呢
```

**Comment by EvilCult** [comment]
3，4行换这个试试。
import tkinter
from tkinter.ttk import *

**Comment by moboard** [comment]
@EvilCult 修改运行出现下面这样的提示：
python guiClass.py

```
Traceback (most recent call last):
  File "guiClass.py", line 5, in <module>
    import tkMessageBox
ImportError: No module named 'tkMessageBox'

```

系统默认用的是python3

**Comment by EvilCult** [comment]
修改方式同ttk。
或者使用python2.7执行项目。
或者使用打包好的app文件。
