### ISSUE TITLE
ubuntu下跑不起？还是说需要特别的config?

### ISSUE THREAD

**Issue by eignil** [EvilCult/Video-Downloader#37]
Traceback (most recent call last):
  File "./main.py", line 13, in <module>
    app.run()
  File "/home/eig/workspace/Video-Downloader/guiClass.py", line 338, in run
    self.__mainWindow()
  File "/home/eig/workspace/Video-Downloader/guiClass.py", line 45, in __mainWindow
    self.__autoUpdate()
  File "/home/eig/workspace/Video-Downloader/guiClass.py", line 305, in __autoUpdate
    if self.cfg['udrate'] == 1:
KeyError: 'udrate'

**Comment by EvilCult** [comment]
好久没在Linux系统下测试过了。。。。
大概是“cfgClass.py”文件119行那里定义的缓存文件目录没有写入权限之类的吧。

**Comment by 1990895346** [comment]
大叔，好久不见你等qq了怎么回事？

**Comment by shockwavemoto** [comment]
Traceback (most recent call last):
File "./main.py", line 13, in 
app.run()
File "/home/eig/workspace/Video-Downloader/guiClass.py", line 338, in run
self.__mainWindow()
File "/home/eig/workspace/Video-Downloader/guiClass.py", line 45, in __mainWindow
self.__autoUpdate()
File "/home/eig/workspace/Video-Downloader/guiClass.py", line 305, in __autoUpdate
if self.cfg['udrate'] == 1:
KeyError: 'udrate'

This is a dependency error
:small_airplane: :small_airplane: :smile:
