### ISSUE TITLE
macOS 10.11.6上启动失败

### ISSUE THREAD

**Issue by feicong** [EvilCult/Video-Downloader#45]
启动失败，在命令行下错误信息如下：
```
$ /Applications/Video\ downloader.app/Contents/MacOS/V
ideo\ downloader 
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "guiClass.py", line 338, in run
  File "guiClass.py", line 45, in __mainWindow
  File "guiClass.py", line 305, in __autoUpdate
KeyError: 'udrate'
Main returned -1
```

**Comment by EvilCult** [comment]
啊。。。。
未获取到配置文件。。。
可能是系统原因首次运行初始化配置文件失败了。。。
这应该是个bug。。。。

稍后会解决，多谢。
